// Topics that have curated seed questions
export const SEED_TOPICS = [
  "norske konger",
  "skifakta",
  "var vikingene her òg?",
  "fysikk",
  "økonomi",
  "biologi",
  "psykologi",
  "matematikk",
  "evolusjon",
  "kjemi",
  "filosofi",
  "nevrovitenskap",
  "språkvitenskap",
  "spillteori",
]

export const TOPICS = [
  "norske konger",
  "skifakta",
  "var vikingene her òg?",
  "fysikk",
  "økonomi",
  "biologi",
  "historie",
  "språkvitenskap",
  "psykologi",
  "matematikk",
  "evolusjon",
  "kjemi",
  "filosofi",
  "nevrovitenskap",
  "astronomi",
  "økologi",
  "informatikk",
  "spillteori",
  "medisin",
  "arkeologi",
  "statistikk",
  "logikk",
  "termodynamikk",
  "genetikk",
  "statsvitenskap",
  "jus",
  "musikkteori",
  "antropologi",
  "kognitiv vitenskap",
  "materialvitenskap",
  "kryptografi",
  "oseanografi",
  "klimavitenskap",
]

export function getRandomTopic(): string {
  return TOPICS[Math.floor(Math.random() * TOPICS.length)]
}
